### ISSUE TITLE
[feat] Allow manually add random dir by a popup window

### ISSUE THREAD

**Issue by LintaoAmons** [LintaoAmons/cd-project.nvim#10]
Something like https://github.com/chrisgrieser/nvim-scissors 's popup window.

So user can add any dir popup in their mind.

Two sequential vim.input is also acceptable.

![image](https://github.com/LintaoAmons/cd-project.nvim/assets/95092244/c74df932-872a-4f1b-bdc8-b6cf894c6a48)

**Comment by vague2k** [comment]
You mean searching for any specific dir, through the plugin?

**Comment by LintaoAmons** [comment]
not necessarily search for a path.

It should be a new API(CMD) which accepts two user inputs (name, path) and save it directly to DB(json).

**Comment by vague2k** [comment]
> not necessarily search for a path.
> 
> It should be a new API(CMD) which accepts two user inputs (name, path) and save it directly to DB(json).

Manually adding a path would be cool. I can help with this if you'd like.

**Comment by LintaoAmons** [comment]
Yeah! Of course~

**Comment by vague2k** [comment]
Will start working on this tomorrow! will keep you updated

**Comment by vague2k** [comment]
Here's a small commit that add's an api method called `add_project` takes in name and path params and returns a string. I *think* there might be a better way of doing this but let me know what you think.

**Comment by LintaoAmons** [comment]
I think you can just raise a PR, it's easier to review~ 
Also we can still have some changes along the way

**Comment by vague2k** [comment]
Sure, i'll do that as soon as i can, been a bit busy this week

**Comment by LintaoAmons** [comment]
No problem, I thought you were pushing commits here.
No hurry~

**Comment by vague2k** [comment]
Hey! haven't forgot about this... sorry it's been a while I took this week to finally get around to managing my dotfiles and rewriting my nvim config. PR will be made in the next couple days, you could label this issue pending if you'd like :)

**Comment by LintaoAmons** [comment]
Oh bro, take your time, no hurry~
I just create another `bookmark` plugin
LOL

**Comment by vague2k** [comment]
Made a commit to my fork, uses vim.fn.input instead of vim.ui.input. see comment in commit, Let me know if any changes or updates.

**Comment by vague2k** [comment]
i tried using 2 Ui.inputs nested, but the behavior of the variables inside the callbacks was weird, and the code felt fragile. If you wanna take a try at it i'd love to see how you'd approach it

**Comment by vague2k** [comment]
Plz test and let me know what you think of the implementation!
