### ISSUE TITLE
Bug: Manually adding project path

### ISSUE THREAD

**Issue by PixsaOJ** [LintaoAmons/cd-project.nvim#13]
When using `CdProjectManualAdd`

You have option to select path in Telescope and it goes like this: `Desktop/Projects/lala....`.

But this path is missing `~/` in the begging so it throws error. Error itself is not helpful:

```

E5108: Error executing lua: ...azy/cd-project.nvim/lua/cd-project/adapter/telescope.lua:85: attempt to concatenate a nil value
stack traceback:
	...azy/cd-project.nvim/lua/cd-project/adapter/telescope.lua:85: in function 'on_confirm'
	/usr/share/nvim/runtime/lua/vim/ui.lua:103: in function 'input'
	...azy/cd-project.nvim/lua/cd-project/adapter/telescope.lua:80: in function 'run_replace_or_original'
	...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:269: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:2
```

**Comment by LintaoAmons** [comment]
Okie, I would like to make it simple to just take user's input as the value to add a project path

**Comment by vague2k** [comment]
Hey! I implemented this so maybe I can help.. What OS are you on?

**Comment by PixsaOJ** [comment]
I am on Manjaro and terminal is alacritty. Shell is zsh if it matters

**Comment by vague2k** [comment]
> I am on Manjaro and terminal is alacritty. Shell is zsh if it matters

Using on my arch system with alacritty, kitty, and konsole, all using zsh... 

I tested on [my fork](https://github.com/vague2k/cd-project.nvim), which is up to date with upstream besides commenting out the lines where the entry for this command is called.

It seems to work as intended? How are you calling / using the command?

**Comment by PixsaOJ** [comment]
I don't have shortcut for it. I simply type command and telescope opens. I think issue is telescope returning "~/" less value.

Ill check my configuration tomorrow to provide more details

**Comment by vague2k** [comment]
> I think issue is telescope returning "~/" less value.

In my implementation the telescope picker using `~` as the CWD to search through, so I find it a bit odd that your having this bug. even if you end up solving this please get let me know I'd love to know what happened. 

If you wanna look at the code yourself, the comment explaining this, along with the function that `CdProjectManualAdd` calls is [here](https://github.com/LintaoAmons/cd-project.nvim/blob/9a0b83e1bedf03cae5f0087ed2e5b3f523f50c77/lua/cd-project/adapter/telescope.lua#L64)

**Comment by PixsaOJ** [comment]
Sorry for late response, was busy.

I am little bit lost. I write command `CdProjectManualAdd` but I don't get Telescope prompt, I get normal "Add a project path: " promt. I think i missed something and created issue with wrong description?

**Comment by vague2k** [comment]
Yes in the latest version the telescope picker for `CdProjectManualAdd` is disabled due to the original author wanting to rework it. If you wanna be able to use it you can fork it and uncomment [lines 14-17 here](https://github.com/LintaoAmons/cd-project.nvim/blob/9a0b83e1bedf03cae5f0087ed2e5b3f523f50c77/lua/cd-project/adapter/init.lua#L14)

**Comment by PixsaOJ** [comment]
I will close this, I'm fine with manual. 

Is there a way to add nvim-cmp path complition to it tough?

**Comment by vague2k** [comment]
> Is there a way to add nvim-cmp path complition to it tough?

Currently no

**Comment by LintaoAmons** [comment]
Okie, guys, sorry for the late explaination.

So there's another issue related to this function, then I made this change.

The user journey that I image is:
1. user already have some path in mind
2. user wants to add that path as a project
3. user trigger the command and put the path in
4. confirm and save it

So I just remove the extra work and allow user put any random string in their mind as the path. 

@vague2k we could have one more command for the `Search then Add` scenario

**Comment by vague2k** [comment]
> Okie, guys, sorry for the late explaination.
> 
> So there's another issue related to this function, then I made this change.
> 
> The user journey that I image is:
> 
>     1. user already have some path in mind
> 
>     2. user wants to add that path as a project
> 
>     3. user trigger the command and put the path in
> 
>     4. confirm and save it
> 
> 
> So I just remove the extra work and allow user put any random string in their mind as the path.
> 
> @vague2k we could have one more command for the `Search then Add` scenario

I wouldn't be apposed to this, I can open a seperate issue for this feature if you'd like

**Comment by LintaoAmons** [comment]
Sounds good, thanks bro
