### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by HakonHarnes** [LintaoAmons/cd-project.nvim#2]
FYI: There's a typo in the README towards the end: 

"FIND MORE **UESR** FRIENDLY PLUGIN MADE BY ME". 

It should probably also be "PLUGINS", not "PLUGIN". 

Same typo in https://github.com/LintaoAmons/scratch.nvim.

**Comment by LintaoAmons** [comment]
Thx for point that out!
Still need more practice to improve my English~
