### ISSUE TITLE
need start this plugin after noice.nvim

### ISSUE THREAD

**Issue by gxt-kt** [LintaoAmons/cd-project.nvim#26]
If this plugin start before noice.nvim, then open a directory there will create a noice buffer and print :
```plaintext
"method called"
```
![image](https://github.com/LintaoAmons/cd-project.nvim/assets/47113549/2c0d4032-6144-44d9-aa71-f56ad6b28183)

So i try to add following to init plugin:
```lua
{
  "LintaoAmons/cd-project.nvim",
  dependencies = { "folke/noice.nvim" },
  config = function() end,
},
```
and slove the problem.

**Comment by LintaoAmons** [comment]
Sorry, I forget the delete the test print statement in the code, it should be already fix by now
