### ISSUE TITLE
"auto_register_project" not disabled

### ISSUE THREAD

**Issue by steakhutzeee** [LintaoAmons/cd-project.nvim#27]
Hi, just updated to latest version. Disabled the automatic project register as from docs:

```
local M = {
  "LintaoAmons/cd-project.nvim",
}

function M.config()
  require("cd-project").setup {
    auto_register_project = false,
    projects_picker = "telescope",
    hooks = {
      {
        callback = function(_)
          vim.cmd("Telescope find_files")
        end,
      },
    },
  }
  
  local opts = { noremap = true, silent = true }
  local keymap = vim.api.nvim_set_keymap

  keymap("n", "<c-p>", "<cmd>CdProject<CR>", opts)
end

return M
```

But projects are still automatically added. Ideas?

**Comment by LintaoAmons** [comment]
Sorry, cause the setup function will automatically been called in `plugin/cd-project.lua` with default config, so I changed the default config to false

**Comment by steakhutzeee** [comment]
Hi, if I am not wrong I tried also without the option even set and this still occurred.

How should it be set to disable it?

Thank you!

**Comment by LintaoAmons** [comment]
Can you update the plugin and try it again?

**Comment by steakhutzeee** [comment]
Yes, thank you!

Updated and removed the option. It's disabled by default and is working well.

**Comment by LintaoAmons** [comment]
Thanks for your reporting
