### ISSUE TITLE
Telescope integration

### ISSUE THREAD

**Issue by schuebel** [LintaoAmons/cd-project.nvim#3]
How do I integrate this with Telescope? Can you share a config example?

**Comment by LintaoAmons** [comment]
Sorry, currently it uses vim.ui to find the saved directories,
I'm already add an issue as a place holder for telescope integration.
So for now, there's no out-of-box telescope integration, please wait for a while...

https://github.com/LintaoAmons/cd-project.nvim/issues/1

**Comment by schuebel** [comment]
Thanks for the reply. How did you achieve what can be seen in the demo gif?

**Comment by LintaoAmons** [comment]
It's https://github.com/stevearc/dressing.nvim
