### ISSUE TITLE
Issue with jq

### ISSUE THREAD

**Issue by steakhutzeee** [LintaoAmons/cd-project.nvim#31]
Hi, I'm trying the new version with default jq.

Maybe it's me doing this wrong but if I manually open the `cd-project.nvim.json` and save it, then it is formatted by my json lsp of course. But if I try to add a project directly with `CdProjectAdd` for example, it's not.

Should this work out of the box? Do I actually need to download the executable? I tried adding it to PATH with same outcome.

Thank you.

**Comment by LintaoAmons** [comment]
Please type `:lua = vim.fn.executable('jq')`, check the result, if it's 1?

**Comment by steakhutzeee** [comment]
> Please type `:lua = vim.fn.executable('jq')`, check the result, if it's 1?

It shows 0
