### ISSUE TITLE
Feat Request: Set custom names to paths

### ISSUE THREAD

**Issue by vague2k** [LintaoAmons/cd-project.nvim#7]
FIrst of all, amazingly simple plugin. It's **awesome**. 
I see that in the plugin's json. there's a name field for each field. I think It would be neat to be able to show this name in the selection prompt.

After using the plugin a bit more, and reading up on the codebase, I'd be willing to try my hand at implementing this.

**Comment by LintaoAmons** [comment]
Haha, thx~ 

Yeah, I was too lazy to implement it since the plugin is already usable for me~

**Comment by vague2k** [comment]
Would you like me to wait until the telescope integration is finished?

**Comment by LintaoAmons** [comment]
Yeah, otherwise there would be some conflicts~
But can do it now, I already merged that PR

**Comment by vague2k** [comment]
Will start working on it, hopefully I will get a PR soon.

**Comment by vague2k** [comment]
Just commited a change specifcally for the telescope adapter. Totally forgot to implement the feature for `vim.ui`.
Once I implement for `vim.ui`, I'll submit the PR.

**Comment by vague2k** [comment]
> Just commited a change specifcally for the telescope adapter. Totally forgot to implement the feature for `vim.ui`. Once I implement for `vim.ui`, I'll submit the PR.

Just submitted!  #8
