### ISSUE TITLE
Printing unwanted debug message to Noice

### ISSUE THREAD

**Issue by kr40** [LintaoAmons/cd-project.nvim#9]
Amazing plugin, just a little gripe, I am using Noice and this line prints a debug message - 

https://github.com/LintaoAmons/cd-project.nvim/blob/3498ce959a3f41b354df0ef9718c37a6c46763bf/lua/cd-project/api.lua#L46

Is it required or can this be omitted?

**Comment by LintaoAmons** [comment]
Haha, sorry, I will delete it right away

**Comment by LintaoAmons** [comment]
I think I already deleted it~ Can have a look~

**Comment by kr40** [comment]
Hey, thank you so much! I will close this issue!
